// The Vercel build command creates a bundled Node/ESM server artifact first.
// Importing that generated bundle avoids relying on monorepo TypeScript workspace
// resolution inside Vercel's function packager.
// @ts-ignore -- generated by the Vercel build command before function packaging.
import server from "../artifacts/api-server/dist/index.mjs";

export default server;
